//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDRNetsapian
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CallReportingEntities1 : DbContext
    {
        public CallReportingEntities1()
            : base("name=CallReportingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CALL_RECORDS_MASTER> CALL_RECORDS_MASTER { get; set; }
        public virtual DbSet<PROCESSING_STATUS> PROCESSING_STATUS { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<CALL_RECORDS_STAGING> CALL_RECORDS_STAGING { get; set; }
    }
}
