//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDRNetsapian
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALL_RECORDS_MASTER
    {
        public string Dialed__ { get; set; }
        public string From_Device { get; set; }
        public string Orig_Call_ID { get; set; }
        public string From_User { get; set; }
        public string To_Device { get; set; }
        public string To_User { get; set; }
        public string Call_Time { get; set; }
        public string Ringing_Time { get; set; }
        public string Answer_Time { get; set; }
        public string Hangup_Time { get; set; }
        public int Talking_Time { get; set; }
        public int Hold_Time { get; set; }
        public int Duration__Sec_ { get; set; }
        public int ACW { get; set; }
        public string Pre_Talk_Time { get; set; }
        public string Release_Reason { get; set; }
        public string Disposition { get; set; }
        public string Reason { get; set; }
    }
}
