//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDRNetsapian
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESSING_STATUS
    {
        public System.DateTime START_DATE { get; set; }
        public string FILE_NAME { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
    }
}
